name: Python pkg CI
on:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest --cov=./pysls --cov-report xml
    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
