name: Python pkg CI


on:
  push:
    branches: [ master, dev ]
    paths: 
      - '**.py'

  pull_request:
    branches: [ master ]
    paths: 
      - '**.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install aws-sam-cli
    - name: Delete requirements.txt so as not to disturb the tests
      run: rm requirements.txt
    - name: Test with pytest
      run: pytest --cov=./pysls --cov-report=xml
    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true